import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';
import { TransactionProvider } from '@/context/TransactionContext';
import { ActiveClientProvider } from '@/context/ActiveClientContext';
import { HelpProvider } from '@/components/help/HelpPanel';
import HelpButton from '@/components/help/HelpButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ background: '#ffd9b3' }}
      >
        <HelpProvider>
          <TransactionProvider>
            <ActiveClientProvider>
              {children}
              <Suspense fallback={null}>
                {/* Show one global floating Help button on every page */}
                <HelpButton/>
              </Suspense>
            </ActiveClientProvider>
          </TransactionProvider>
        </HelpProvider>
      </body>
    </html>
  );
}
